### ISSUE TITLE
xgo 1.18 build error

### ISSUE THREAD

**Issue by libsgh** [techknowlogick/xgo#154]
When I build with xgo 1.18, I get an error.
`error obtaining VCS status: exit status 128	Use -builds=false to disable VCS stamping.`

**Comment by xoxys** [comment]
Due to the full error message, it might be an option to set `git config --global --add safe.directory /source` by default in the container?

```
To add an exception for this directory, call:

	git config --global --add safe.directory /source
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
```

**Comment by sungwoncho** [comment]
In my case, the following error occurred:

```
Checking for required docker image techknowlogick/xgo:go-1.18.x... found.
Cross compiling /home/sung/dev/dnote-infra/dnote/scripts/cli/../.....
Enabled Go module support
Building /source/go.mod...
Compiling for linux/amd64...
WORK=/tmp/go-build3141435809
cd /source
git status --porcelain
# cd /source; git status --porcelain
fatal: not a git repository: /source/../.git/modules/dnote
error obtaining VCS status: exit status 128
        Use -buildvcs=false to disable VCS stamping.
Cleaning up build environment...
chown: cannot access '/build/github.com/dnote/dnote*': No such file or directory
2022/04/29 22:38:55 Failed to cross compile package: exit status 1.
Makefile:83: recipe for target 'build-cli' failed
make: *** [build-cli] Error 1
```

Tried to see where `git status --porcelain` is called, but could not find in the source of `xgo`. Any thoughts for a way forward?

**Comment by sungwoncho** [comment]
thanks @techknowlogick. Is there a guide for contributing? Would like to help, and wasn't sure how to build and test locally.

**Comment by xoxys** [comment]
@techknowlogick I've created a PR and tested it locally if you have time to review :)

@sungwoncho There is AFAIK no contribution guide, but you can take a look at the GitHub Actions configuration to see how the Images are build https://github.com/techknowlogick/xgo/blob/main/.github/workflows/build_images.yml In this case is relatively easy:

```
docker build -f docker/base/Dockerfile docker/base/ -t techknowlogick/xgo:base
docker build -f docker/go-1.18.1/Dockerfile docker/go-1.18.1/ -t techknowlogick/xgo:go-1.18.1
```

Besides that, your issue seems to be different. The directory where your source code is located doesn't seem to be a git repository. Just running `git init` in this directory should fix it. @techknowlogick wouldn't it make sense to allow passing `-buildvcs` to go build as well?

**Comment by techknowlogick** [comment]
Thanks @xoxys I made a minor change to your PR, and have merged the result. A new version of golang was just released, so this will be included when xgo builds that new release.
