### ISSUE TITLE
`go-1.19.3` tag starts complaining about missing go.mod file

### ISSUE THREAD

**Issue by m90** [techknowlogick/xgo#187]
I've been using `xgo` for a while now to build cross-platform binaries for my application. Currently, I'm on `techknowlogick/xgo:go-1.19.x`.

Starting today, builds would start failing with the following error message:

```
 > [compiler 10/12] RUN chmod +x ./compile.sh && ./compile.sh && rm ./compile.sh:
#77 0.388 Cross compiling github.com/offen/offen/server/cmd/offen...
#77 0.431 Go modules are enabled but go.mod was not found in the source folder.
#77 0.431 2022/11/24 10:03:14 Failed to cross compile package: exit status 10.
```

The command from `compile.sh` looks like this:

```
  xgo \
    --targets=$TARGETS \
    --tags 'osusergo netgo static_build sqlite_omit_load_extension' \
    --ldflags="-linkmode external -extldflags '$LDFLAGS' -s -w -X github.com/offen/offen/server/config.Revision=$GIT_REVISION" \
    github.com/offen/offen/server/cmd/offen
```

When this error is raised, there is a `go.mod` file in `github.com/offen/offen/server/go.mod`.

I assume this behavior was introduced in the recent `go-1.19.3` release as downgrading to `go-1.19.2` makes the build pass again.

Am I doing something wrong when building my binaries or does `go-1.19.3` contain a regression somehow?

This is how assets are copied into building image:

```
FROM techknowlogick/xgo:go-1.19.x as compiler

ARG rev
ENV GIT_REVISION=$rev
ARG targets
ENV TARGETS=$targets

COPY ./server /go/src/github.com/offen/offen/server

ENV GOPATH /go
WORKDIR /build

COPY ./build/compile.sh .
RUN chmod +x ./compile.sh && ./compile.sh && rm ./compile.sh
```

**Comment by techknowlogick** [comment]
This could be related to https://github.com/techknowlogick/xgo/commit/dc59b5d9597da98682b4a4a22ae517f7fd6273ad which changes the `GO111MODULES` detection behaviour.

**Comment by kolaente** [comment]
I've noticed that as well: https://drone.kolaente.de/vikunja/api/4498/2/6

**Comment by kolaente** [comment]
I think the problem is caused by this line here:

 https://github.com/techknowlogick/xgo/blob/63bb785ab1d3430bc02b75a7722de346d79e116a/docker/base/build.sh#L170

This one was changed during #180 but only formatted differently. This leaves two conclusions:

1. Either the `if` surrounding the `sed` call was not executed at all before
2. Or the call always failed, the rest of the script just ignored it and proceeded anyway

I think the path should not be hardcoded. This might work when running xgo via the shell but once running in CI or similar where xgo is called directly that path might be different. Shouldn't the current working directory work as well?

**Comment by techknowlogick** [comment]
@kolaente I wonder why it fails for you, as you have a similar build process to Gitea.

**Comment by kolaente** [comment]
@techknowlogick is gitea using the latest image?

**Comment by techknowlogick** [comment]
Gitea is using :go-1.19.x (which is the same as :latest)

**Comment by 6543** [comment]
Ah ... this use a absolite path ... woodpecker also had to stick to an older version

**Comment by 6543** [comment]
https://github.com/woodpecker-ci/woodpecker/pull/1499/files

**Comment by techknowlogick** [comment]
Ah yeah, it's working for Gitea as the workspace is hardcoded as /source https://github.com/go-gitea/gitea/blob/main/.drone.yml#L685-L687 so go.mod is copied in

**Comment by 6543** [comment]
well I dont think there should be a hardcoded workspace asumed :/

**Comment by zeripath** [comment]
So looking at `xgo.go` if it detects that there is a `go.mod` present in the root of the repository it will automount the repository as `/source`

https://github.com/techknowlogick/xgo/blob/a9c797386a02db668ddf84a7a10996e5c57188da/xgo.go#L270-L273

https://github.com/techknowlogick/xgo/blob/a9c797386a02db668ddf84a7a10996e5c57188da/xgo.go#L386-L406

Do we have an example of the repo in question?

---

There's essentially a conflict with the way that `xgo.go`, `go` and the docker `build.sh` are detecting go modules. 

I guess this might need to be rethought a bit. Perhaps the source-repo should just be mounted at `/source` always? Or the decision about where the GOPATH is should be handled in the `base.sh`?

**Comment by zeripath** [comment]
OK, so re-reading the initial comment - the problem here is on Line 269:

https://github.com/techknowlogick/xgo/blob/a9c797386a02db668ddf84a7a10996e5c57188da/xgo.go#L269-L273

`config.Repository` is `flag.Args()[0]` i.e. `"github.com/offen/offen/server/cmd/offen"` 

Thus `useModules` remains `false` as it is never set and so the `/source` mount point is never run.

Then the changes in dc59b5d9597da98682b4a4a22ae517f7fd6273ad apply and overrule GOMODULES and force the use of `/source`.

---

So there are two bugs:

* Either dc59b5d9597da98682b4a4a22ae517f7fd6273ad is completely wrong and we should not attempt to determine GOMODULES on a per go version basis - or we should always mount the current source as `/source` <- I think this second option is probably the correct one.
  - I'm confused as to how this was ever building in the first place - @m90 are you building within the GOPATH? That's the only way I can see that the source code was being passed to the docker build...
* We should be able to cope with relative paths in the config.Repository.

(As an aside, I think there's another issue with `$NAME` determination in `build.sh` )

**Comment by m90** [comment]
> I'm confused as to how this was ever building in the first place - @m90 are you building within the GOPATH? That's the only way I can see that the source code was being passed to the docker build...

Yes. I am. GOPATH is at `/go` and source is at `/go/src/github.com/offen/offen/server`

**Comment by kolaente** [comment]
Not 100% sure but couldn't we assume the current package always uses modules? Since all supported go versions definitely have modules. If we make that assumption we could get rid of all code used to detect module usage and avoid bugs like this.

**Comment by techknowlogick** [comment]
> Not 100% sure but couldn't we assume the current package always uses modules?

IIRC golang has [deprecated GOPATH](https://github.com/golang/go/issues/30329), although perhaps instead of picking if to use modules or not based on golang version, we should revert back to triggering based on `GO111MODULES` env var?

(as a note, my comment is mostly restating what has already been said in the thread, not intending to say it as if it were a novel idea, but more to agree with the idea)

**Comment by zeripath** [comment]
Having thought a bit more on this. We have a few options:

1. Always run in module aware mode - always set `$GO111MODULES = "on"` and drop all the GOPATH logic.
2. Provide an option to switch between module modes
3. Or infer the module mode by using the `$GO111MODULES` env var when running `xgo`

My PR was incorrect as it failed to recognise how `xgo.go` and `build.sh` interacted so there is definitely a bug.

---

## What are the module modes?
 
### `on` / module-aware mode

This is the default for go >= 1.16 if `$GO111MODULES` is not set.

No attempt is made to find a `go.mod` file. `$GOPATH` is essentially ignored except that `$GOPATH/pkg/mod` is used as the default for `$GOMODCACHE` module cache and `$GOPATH/bin` is the default `$GOBIN`

### `auto`

This is the default for go < 1.16 >=1.13 if `$GO111MODULES` is not set.

`on` is used if `go.mod` is present in the current directory or any parent up to the root, otherwise gopath mode is used

### `off` / gopath mode
 
The default mode prior to 1.13.

The project should be built inside in the `$GOPATH/src` and dependencies are searched for from there.

## How should/could `xgo` handle each of these modes?

Well we will need to consider what happens when `xgo` is called with a directory versus when it is called with a module/url/etc.

## `on` / module-aware / <- THIS SHOULD BE THE DEFAULT

This is a simple case - module support is assumed and therefore we do not need to provide a go path or look into the source code. 

For calling xgo with a directory we will need to mount the source code on say `/source` as we do at present.
For calling xgo with an url/module we should use `go get` to get the source to say `/source`. <- WE ARE NOT DOING THIS PROPERLY RIGHT NOW

It is likely we should be mounting `${host:GOPATH}/pkg/mod` on the docker and putting that as `$GOMODCACHE` or providing an option to do that, and we should also set `$GO111MODULES` to `"on"` in the container.

### `auto`

This is a bit more difficult. For paths we can try to find the `go.mod` etc. and then set `$GO111MODULES` to `on` or `off` as appropriate and create a GOPATH. 

For url/modules perhaps we should just not allow this? We could support it by copying the logic to do the determination into build.sh.

### `off` / gopath-mode

This requires creating the GOPATH etc. which xgo has logic to do, but again we'll need to explicitly set `$GO111MODULES` to `"off"` in the container.

**Comment by zeripath** [comment]
So the situation for `xgo package` is more complicated as `go get -d` will not work without a go.mod in modern go... so the use of `go get -v -d` in build.sh will require an explicit `GO111MODULE=off` which is likely to be at most a temporary fix.

To get a thing which will work when GO111MODULE disappears I think we might need to do something like:

```
mkdir tmp
go mod init xgo.temporary.build
go get -v -d ${PACKAGE}
```

and then somehow work out where the package can be found...

**Comment by zeripath** [comment]
OK I think have something that should work

**Comment by m90** [comment]
I just tried building my application using the latest Docker hub tag (`techknowlogick/xgo:go-1.19.5` to be exact which I think :tm: contains #189 already), and now I am seeing a different error, which is:

```
#77 52.58 sed: can't read /source/go.mod: No such file or directory
#77 52.58 2023/01/10 20:44:14 Failed to cross compile package: exit status 2.
```

I have to admit that I am pretty sure it might well be me who's doing something wrong here, as this build pipeline that is now breaking hasn't really been touched ever since I set it up, which was when this image was still owned by `karalabe` and go modules didn't really exist yet. It just kept building, so I assumed everything was still ok.

Here is what I do exactly (in a terribly slow but very reliable all-Dockerfile build):

```
FROM techknowlogick/xgo:go-1.19.2 as compiler

ARG rev
ENV GIT_REVISION=$rev
ARG targets
ENV TARGETS=$targets
ARG ldflags
ENV LDFLAGS=$ldflags

COPY ./server /go/src/github.com/offen/offen/server
COPY --from=script /code/script/dist /go/src/github.com/offen/offen/server/public/static
COPY --from=vault /code/vault/dist /go/src/github.com/offen/offen/server/public/static
COPY --from=auditorium /code/auditorium/dist /go/src/github.com/offen/offen/server/public/static
COPY --from=notice /code/NOTICE /go/src/github.com/offen/offen/server/public/static/NOTICE.txt
COPY ./locales/* /go/src/github.com/offen/offen/server/public/static/locales/

ENV GOPATH /go
WORKDIR /build

COPY ./build/compile.sh .
RUN chmod +x ./compile.sh && ./compile.sh && rm ./compile.sh
RUN [ ! -f ./offen-linux-arm-7 ] || mv ./offen-linux-arm-7 ./offen-linux-arm-v7

COPY --from=notice /code/NOTICE ./
```

`compile.sh` looks like:

```
if [ -z "$LDFLAGS" ]; then
  xgo \
    --targets=$TARGETS \
    --tags 'osusergo netgo static_build sqlite_omit_load_extension' \
    --ldflags="-s -w -X github.com/offen/offen/server/config.Revision=$GIT_REVISION" \
    github.com/offen/offen/server/cmd/offen
else
  xgo \
    --targets=$TARGETS \
    --tags 'osusergo netgo static_build sqlite_omit_load_extension' \
    --ldflags="-linkmode external -extldflags '$LDFLAGS' -s -w -X github.com/offen/offen/server/config.Revision=$GIT_REVISION" \
    github.com/offen/offen/server/cmd/offen
fi
```

Is there anything unexpected that I am doing here? Should I copy my Go code into `/source` instead?

**Comment by zeripath** [comment]
Oh damn.

Stick an --out option on your xgo comment

**Comment by zeripath** [comment]
https://github.com/techknowlogick/xgo/blob/1fd3d5b59de331b225f0a2cd9174c1b1d3c8fadb/docker/base/build.sh#L164-L168

This also needs to test if -d /source
